---
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Testing
          command: make test
      - run:
          name: Build
          command: make build