---
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: chmod +x scripts/coverage.sh
      - run:
          name: Testing
          command: make test-ci
      - run: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Build
          command: make build