---
name: Run tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:

  go-build:
    runs-on: ubuntu-20.04
    # defaults:
    #   run:
    #     working-directory: go

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14'

      - name: Running unit tests
        run: make test-coverage
